services:
  kong:
    image: kong:3.9.2
    container_name: kong-gateway
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /etc/kong/kong.yml
      KONG_PROXY_LISTEN: 0.0.0.0:8000
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      # Pass Environment Variables into Container
      REDIS_HOST: ${REDIS_HOST:-redis}
      REDIS_PORT: ${REDIS_PORT:-6379}
      REDIS_PASSWORD: ${REDIS_PASSWORD:-""}
      CLERK_ISSUER_URL: ${CLERK_ISSUER_URL:-""}
      CLERK_JWT_PUBLIC_KEY: ${CLERK_JWT_PUBLIC_KEY:-""}
      GATEWAY_INTERNAL_SECRET: ${GATEWAY_INTERNAL_SECRET:-ecommerce-internal-trust-2026-xyz}
    volumes:
      - ./kong.yml:/etc/kong/kong.yml:ro
    ports:
      - "8000:8000"
      - "127.0.0.1:8001:8001"
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - e-commerce-microservices_default

networks:
  e-commerce-microservices_default:
    external: true
